### ISSUE TITLE
Crafty engine upgrade to 0.6.4

### ISSUE THREAD

**Issue by sashman** [mucaho/npm_crafty#21]
Is there any scope to upgrade this to use the 0.6.4 crafty? If not what needs to be done and I could create a pull request?

**Comment by mucaho** [comment]
Hi, [it's already done](https://github.com/mucaho/npm_crafty/tree/use_npm). I'm just waiting for the new version to be released on the node package manager, so this library can require it.

**Comment by sashman** [comment]
Sweet!

**Comment by mucaho** [comment]
Updated to Crafty `v0.7.0` via 8f4e33cae0b060a4b8ac4c6eaf84f042f98fcc58.

**Comment by sashman** [comment]
Awesome, just read this! Will try and get around ot trying it out as soon as I get some free time! Thanks a bunch :smile:
